nacos:
  address: 192.168.33.20:8848
  namespace: prod


server:
  address: 0.0.0.0
  port: 8899
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: my-gateway
  main:
    allow-circular-references: true
    banner-mode: off
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  config:
    import: optional:nacos:${spring.application.name}
  cloud:
# 这个注释掉就没有 动态路由了, {@link org.springframework.cloud.gateway.discovery.GatewayDiscoveryClientAutoConfiguration.ReactiveDiscoveryClientRouteDefinitionLocatorConfiguration}
#    discovery:
#      reactive:
#        enabled: true
    nacos:
#      username: ${nacos.username}
#      password: ${nacos.password}
      discovery:
#        watch-delay: 5000
        watch:
          enabled: true  # 启用服务监听
        serverAddr: ${nacos.address}
        namespace: ${nacos.namespace}
        group: http  # 只发现这个group下面的
        # 心跳间隔：5s
        heartBeatInterval: 5000
        # 15s 不上报 -> unhealthy
        heartBeatTimeout: 15000
        # 30s 不上报 -> 剔除实例
        ipDeleteTimeout: 30000
        cluster-name: DEFAULT
        fail-fast: true # 强依赖nacos失败就不启动
        ephemeral: true
      config:
        serverAddr: ${nacos.address}
        namespace: ${nacos.namespace}
        file-extension: yaml
        refresh-enabled: true
    loadbalancer:
      nacos:
        enabled: true  # 生产要看下有没有这个, 如果有这个就代表跨集群了  A cross-cluster call occurs
      configurations: health-check  # 启用健康检查 ServiceInstanceListSupplier
      health-check:
        interval: 10s
#        initialDelay: 5s  # todo 这个有点坑 , 健康检查的初始延迟时间，即负载均衡器启动后等待多久才开始执行第一次健康检查，用于给后端服务足够的启动时间
        refetchInstances: true  # 关键：定期从注册中心重新获取实例
        refetchInstancesInterval: 5s  # 重新获取间隔
        repeatHealthCheck: true  # 是否循环健康检查
        updateResultsList: true # 是否根据检查结果实时更新负载均衡器的缓存列表
        path:
#          default: /actuator/health/readiness
          user-demo: /api/user-demo/actuator/health/readiness  # 后续这个需要动态生成
      cache:
        enabled: true
        ttl: 10s
        capacity: 2048  # 默认是256 超过了就进行驱逐
    gateway.server.webflux:
      enabled: true
      # 默认下面2个是true, 但是这个在高并发下比较影响性能
      # 是在 org.springframework.cloud.gateway.config.GatewayMetricsAutoConfiguration 这个类下面的
      metrics:
        enabled: true
      observability:
        enabled: true
#      discovery:
#        locator:
#          # 启用服务发现, 并把服务名转小写
#          enabled: true
#          lowerCaseServiceId: true # 忽略服务名的大小写
      httpclient:
        connect-timeout: 3000          # 连接超时，毫秒
        response-timeout: 10s          # 响应超时
        pool:
          type: fixed                  # 固定连接池（生产推荐）
          leasing-strategy: lifo        # 后进先出, 用热连接
          max-connections: 200         # 最大连接数, 每个ip:port 200
          acquire-timeout: 3000        # 获取连接超时
          max-idle-time: 30s           # 最大空闲时间
          max-life-time: 60s           # 连接最大存活时间, 会强制杀掉所有连接，包括 WebSocket 连接
          eviction-interval: 20s       # 定期清理空闲连接
          metrics: true                # 启用连接池指标
      routeFilterCacheEnabled: false # 路由过滤器缓存, 这个如果要缓存要注意一下共享变量, 所有请求相关的数据都存储在 ServerWebExchange 的 attributes 中
      global-filter: # 全局过滤器, 内置默认的
        reactive-load-balancer-client:
          enabled: true  # 不想用可以关掉
#      default-filters: # 默认过滤器, 可以有多个
#        - StripPrefix=1  # 去掉url里面的第一段进行转发
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
#        - RemoveRequestHeader=Cookie  # 根据需要移除敏感头
      routes:
        # http://127.0.0.1:8899/api/user-demo/test
        - id: user_route
          uri: lb://user-demo
          predicates:
            # 有很多内置的 predicate , https://springdoc.cn/spring-cloud-gateway/#gateway-request-predicates-factories
            - Path=/api/user-demo/**
            - Test1Predicate=GET
#            - PrefixPath=/api/user-demo  # url前面加一些固定的前缀
          filters:
            # StripPrefixGatewayFilterFactory
#            - StripPrefix=1  # 去掉url里面的第一段进行转发
            - name: Test1
              args:
                prefix: abc
            # PrefixPathGatewayFilterFactory允许你在对应的路由请求前增加前缀。例如实例配置中的请求/user，最后转发到目标服务的路径变为/user/hello
#            - PrefixPath=/mypath
# ======================== websocket ==================================================
        # to run server $ wscat --listen 9000
        # to run client  $ wscat --connect ws://localhost:8080/echo
#        - id: websocket_test
#          uri: ws://localhost:9000
#          order: 9000
#          predicates:
#            - Path=/echo
# =================== 权重 ======================================================
#        - id: user-service-prod
#          uri: http://www.iocoder.cn
#          predicates:
#            - Path=/**
#            - Weight=user-service, 90   # 第一个参数为权重分组，需要配置成相同，一般和服务名相同即可；第二个参数为权重比例
#        - id: user-service-canary
#          uri: https://www.oschina.net
#          predicates:
#            - Path=/**
#            - Weight=user-service, 10




#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    org.springframework.cloud.loadbalancer: trace
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG



# 路由都是在这个类 org.springframework.cloud.gateway.actuate.GatewayControllerEndpoint
# 访问 http://127.0.0.1:8899/actuator/gateway/routes

# GET    /globalfilters   // 返回全局 Filter 列表
# GET    /routefilters    // 每个路由的 filter
# POST   /refresh         // 刷新路由缓存
# GET    /routes          // 路由列表
# GET    /routes/{id}     // 指定路由的信息
# POST   /routes/{id}     // 创建路由
# DELETE /routes/{id}     // 删除路由
management:
  endpoints:
    web:
      exposure:
#        include: health,info,metrics,prometheus
        include: '*' # 默认只开放 health,info
  endpoint:
    gateway:
      access: unrestricted  # read-only 只读, unrestricted 可读写(创建/删除路由)
    health:
      probes:
        enabled: true
        show-details: always
